language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
env:
  - PLATFORMIO_CI_SRC=examples/simple/simple.ino
install:
  - pip install -U platformio
script:
  - platformio ci --lib="." --board=d1_mini
